# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Alex's Blog
tagline:          'The Jekyll Butler'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://blckshrk.github.io/

author:
  name:           'Alexandre Bonhomme'
  url:            https://alexandrebonhomme.com

paginate:         1

# Custom vars
version:          1.0.0

