# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '@blckshrk'
tagline:          ''
description:      ''
url:              http://blog.alexandrebonhomme.com

author:
  name:           'Alexandre Bonhomme'
  url:            http://alexandrebonhomme.com

paginate:         10

# Custom vars
version:          0.1.0

# Plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

